# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

try-except көмегімен пайдаланушы енгізетін екі санды бөліңіз (қателерді өңдеңіз).
"""

try:
  number = int(input("Санды енгізіңіз:"))
  result = 625/number
except ZeroDivisionError:
  print("0-ge boluge bolmaudy!")
except ValueError:
  print("Tek sandy engziniz!")
else:
  print("Bagdarlama ayaktaldy")

try:
  number = int(input("Санды енгізіңіз:"))
  result = 625/number
except ZeroDivisionError:
  print("0-ge boluge bolmaudy!")
except ValueError:
  print("Tek sandy engziniz!")
else:
  print("Bagdarlama ayaktaldy")

try:
  number = int(input("Санды енгізіңіз:"))
  result = 625/number
except ZeroDivisionError:
  print("0-ge boluge bolmaudy!")
except ValueError:
  print("Tek sandy engziniz!")
else:
  print("Bagdarlama ayaktaldy")

"""Өз модуліңізді (mymath.py) құрып, add, sub, mul, div функцияларын жазыңыз."""

# mymath.py
def add(a, b, c):
  return a + b + c
def sub(a, b, c):
  return a - b -c
def mul(a, b, c):
  return a * b * c
def div(a, b, c):
  return a / b / c

# module1.py
import mymath
print (mymath.add(17, 18, 30))

# module2.py
import mymath
print (mymath.sub(17, 18, 30))

# module3.py
import mymath
print (mymath.mul(17, 18, 30))

# module4.py
import mymath
print (mymath.div(17, 18, 30))

"""NumPy арқылы 10 элементтен тұратын кездейсоқ массив жасап, оның орта мәнін, максимум және минимумын табыңыз.

"""

pip install numpy

import numpy as np
a = np.array([100, 102, 103, 20, 22, 23, 75, 86, 94, 37])
print(np.mean(a))

a = np.array([100, 102, 103, 20, 22, 23, 75, 86, 94, 37])
print("maximum:", np.max(a))
print("minimum:", np.min(a))